.TH "C:/Users/fabian.franz/Documents/Visual Studio 2012 Directory Reference" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/fabian.franz/Documents/Visual Studio 2012 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProjects\fP"
.br
.in -1c
