.TH "Download.HttpWebRequest_BeginGetResponse" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Download.HttpWebRequest_BeginGetResponse \- 
.SH SYNOPSIS
.br
.PP
.SS "Statische öffentliche Attribute"

.in +1c
.ti -1c
.RI "static ManualResetEvent \fBallDone\fP = new ManualResetEvent(false)"
.br
.in -1c
.SH "Dokumentation der Datenelemente"
.PP 
.SS "ManualResetEvent Download\&.HttpWebRequest_BeginGetResponse\&.allDone = new ManualResetEvent(false)\fC [static]\fP"
Information if done 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
