.TH "md__r_e_a_d_m_e" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- \fBTestForWebUntis\fP 
Main project directory of the API Team
.PP
Open the sln file to use the project\&.
.PP
.IP "\(bu" 2
Project type C#
.IP "\(bu" 2
WP7 SDK 2010 Project
.PP
.PP
Code directory of the API Team
.PP
Open the sln file in the directory above to use the project\&.
.PP
.SH "MainPage\&.xaml"
.PP
.PP
This file contains an UI for testing purposes only 
.SH "MainPage\&.xaml\&.cs"
.PP
.PP
Code for the Testing UI 
.SH "App\&.xaml\&.cs"
.PP
.PP
App Initalisation 
.SH "WebUntis\&.cs"
.PP
.PP
Contains the Code from the API Team\&. For Documentation please see \fCDocumentation Directory\fP 
