.TH "TestForWebUntis.App" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestForWebUntis.App \- 
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von Application, Application und Application\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBApp\fP ()"
.br
.RI "\fIKonstruktor für das Application-Objekt\&. \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SS "Propertys"

.in +1c
.ti -1c
.RI "PhoneApplicationFrame \fBRootFrame\fP\fC [get, set]\fP"
.br
.RI "\fIBietet einen einfachen Zugriff auf den Stammframe der Phone-Anwendung\&. \fP"
.in -1c
.SH "Beschreibung der Konstruktoren und Destruktoren"
.PP 
.SS "TestForWebUntis\&.App\&.App ()\fC [inline]\fP"

.PP
Konstruktor für das Application-Objekt\&. 
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "void TestForWebUntis\&.App\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent 
.SS "void TestForWebUntis\&.App\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent 
.SH "Dokumentation der Propertys"
.PP 
.SS "PhoneApplicationFrame TestForWebUntis\&.App\&.RootFrame\fC [get]\fP, \fC [set]\fP"

.PP
Bietet einen einfachen Zugriff auf den Stammframe der Phone-Anwendung\&. \fBRückgabe:\fP
.RS 4
Der Stammframe der Phone-Anwendung\&.
.RE
.PP


.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
