.TH "TestForWebUntis.MainPage" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestForWebUntis.MainPage \- 
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von PhoneApplicationPage, PhoneApplicationPage und PhoneApplicationPage\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.ti -1c
.RI "void \fBInitializeComponent\fP ()"
.br
.RI "\fIInitializeComponent \fP"
.in -1c
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "void TestForWebUntis\&.MainPage\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent 
.SS "void TestForWebUntis\&.MainPage\&.InitializeComponent ()\fC [inline]\fP"

.PP
InitializeComponent 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
