.TH "WebuntisAPI.Types.Teacher" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Teacher \- 
.PP
\fBWebuntisAPI::Types::Teacher\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBfirstname\fP"
.br
.ti -1c
.RI "String \fBlastname\fP"
.br
.ti -1c
.RI "String \fBshortname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWebuntisAPI::Types::Teacher\fP\&. 

The Structure to save information about a teacher 
.SH "Member Data Documentation"
.PP 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.firstname"
Field containing firstname 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.lastname"
Field containing lastname 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.shortname"
Field containing the shortname e\&.g\&. LED 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
