.TH "WebuntisAPI.Types" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types \- 
.PP
\fBWebuntisAPI::Types\fP Namespase\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTeacher\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Teacher\fP\&. \fP"
.ti -1c
.RI "struct \fBKlasse\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Klasse\fP\&. \fP"
.ti -1c
.RI "struct \fBSubject\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Subject\fP\&. \fP"
.ti -1c
.RI "struct \fBDepartment\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Department\fP\&. \fP"
.ti -1c
.RI "struct \fBHoliday\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Holiday\fP\&. \fP"
.ti -1c
.RI "struct \fBSchoolyear\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::Schoolyear\fP\&. \fP"
.ti -1c
.RI "struct \fBTimeTableElement\fP"
.br
.RI "\fI\fBWebuntisAPI::Types::TimeTableElement\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBWebuntisAPI::Types\fP Namespase\&. 

This contains the structure-variables for x-Change with the APP (Coding) 
.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
