.TH "WebuntisAPI.Types.TimeTableElement" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.TimeTableElement \- 
.PP
\fBWebuntisAPI::Types::TimeTableElement\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Öffentliche Attribute"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "DateTime \fBdate_lesson\fP"
.br
.ti -1c
.RI "DateTime \fBstartTime\fP"
.br
.ti -1c
.RI "DateTime \fBendTime\fP"
.br
.ti -1c
.RI "int[] \fBclassids\fP"
.br
.ti -1c
.RI "int[] \fBsubjectids\fP"
.br
.ti -1c
.RI "int[] \fBroomids\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBWebuntisAPI::Types::TimeTableElement\fP\&. 

The Structure to save information about an element which is a cell in a table 
.SH "Dokumentation der Datenelemente"
.PP 
.SS "int [] WebuntisAPI\&.Types\&.TimeTableElement\&.classids"
Field containing array of ids of classes 
.SS "DateTime WebuntisAPI\&.Types\&.TimeTableElement\&.date_lesson"
Field containing date of the lesson 
.SS "DateTime WebuntisAPI\&.Types\&.TimeTableElement\&.endTime"
Field containing end of the hour 
.SS "int WebuntisAPI\&.Types\&.TimeTableElement\&.id"
Field containing id 
.SS "int [] WebuntisAPI\&.Types\&.TimeTableElement\&.roomids"
Field containing ids of rooms 
.SS "DateTime WebuntisAPI\&.Types\&.TimeTableElement\&.startTime"
Field containing start of the hour 
.SS "int [] WebuntisAPI\&.Types\&.TimeTableElement\&.subjectids"
Field containing array of ids of subjects 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
