.TH "WebuntisAPI.Types.Subject" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Subject \- 
.PP
\fBWebuntisAPI::Types::Subject\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Öffentliche Attribute"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBlongname\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBWebuntisAPI::Types::Subject\fP\&. 

The Structure to save information about a teacher 
.SH "Dokumentation der Datenelemente"
.PP 
.SS "int WebuntisAPI\&.Types\&.Subject\&.id"
Field containing id 
.SS "String WebuntisAPI\&.Types\&.Subject\&.longname"
Field containing subject e\&.g\&. Deutsch 
.SS "String WebuntisAPI\&.Types\&.Subject\&.name"
Field containing short subject e\&.g\&. D 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
