.TH "WebuntisAPI.Types.Teacher" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Teacher \- 
.PP
\fBWebuntisAPI::Types::Teacher\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Öffentliche Attribute"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBfirstname\fP"
.br
.ti -1c
.RI "String \fBlastname\fP"
.br
.ti -1c
.RI "String \fBshortname\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBWebuntisAPI::Types::Teacher\fP\&. 

The Structure to save information about a teacher 
.SH "Dokumentation der Datenelemente"
.PP 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.firstname"
Field containing firstname 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.lastname"
Field containing lastname 
.SS "String WebuntisAPI\&.Types\&.Teacher\&.shortname"
Field containing the shortname e\&.g\&. LED 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
