.TH "WebuntisAPI.WebUntisConnector" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.WebUntisConnector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWebUntisConnector\fP (String connection, String User, String Password)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
