.TH "WebuntisAPI.Types.Schoolyear" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Schoolyear \- 
.PP
\fBWebuntisAPI::Types::Schoolyear\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "DateTime \fBstartTime\fP"
.br
.ti -1c
.RI "DateTime \fBendTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWebuntisAPI::Types::Schoolyear\fP\&. 

The Structure to save information about a schoolyear, but I think this is NOT important 
.SH "Member Data Documentation"
.PP 
.SS "DateTime WebuntisAPI\&.Types\&.Schoolyear\&.endTime"
Field containing last day of shoolyear 
.SS "int WebuntisAPI\&.Types\&.Schoolyear\&.id"
Field containing id 
.SS "String WebuntisAPI\&.Types\&.Schoolyear\&.name"
Field containing name of shoolyear 
.SS "DateTime WebuntisAPI\&.Types\&.Schoolyear\&.startTime"
Field containing first day of schoolyear 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
