.TH "WebuntisAPI.Types.Department" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Department \- 
.PP
\fBWebuntisAPI::Types::Department\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBlongname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWebuntisAPI::Types::Department\fP\&. 

The Structure to save information about a \fBDepartment\fP - really not important but API gives it 
.SH "Member Data Documentation"
.PP 
.SS "int WebuntisAPI\&.Types\&.Department\&.id"
Field containing id 
.SS "String WebuntisAPI\&.Types\&.Department\&.longname"
Field containing long name of department 
.SS "String WebuntisAPI\&.Types\&.Department\&.name"
Field containing short name of department 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
