.TH "WebuntisAPI.WebUntisConnector" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.WebUntisConnector \- 
.SH SYNOPSIS
.br
.PP
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBWebUntisConnector\fP (Uri connection, String Schule, String User, String Password)"
.br
.ti -1c
.RI "String \fBrunJSONRequest\fP (String Method, String Params)"
.br
.ti -1c
.RI "void \fBdoLogin\fP ()"
.br
.in -1c

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
