.TH "WebuntisAPI.Types.Klasse" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Klasse \- 
.PP
\fBWebuntisAPI::Types::Klasse\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Öffentliche Attribute"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBlongname\fP"
.br
.ti -1c
.RI "int \fBdid\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBWebuntisAPI::Types::Klasse\fP\&. 

The Structure to save information about a Schoolclass in german because class makes problems 
.SH "Dokumentation der Datenelemente"
.PP 
.SS "int WebuntisAPI\&.Types\&.Klasse\&.id"
Field containing id 
.SS "String WebuntisAPI\&.Types\&.Klasse\&.longname"
Field containing classname 
.SS "String WebuntisAPI\&.Types\&.Klasse\&.name"
Field containing short classname 

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
