.TH "WebuntisAPI.Types.Holiday" 3 "Wed Mar 20 2013" "WebuntisAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI.Types.Holiday \- 
.PP
\fBWebuntisAPI::Types::Holiday\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBlongname\fP"
.br
.ti -1c
.RI "DateTime \fBstartTime\fP"
.br
.ti -1c
.RI "DateTime \fBendTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWebuntisAPI::Types::Holiday\fP\&. 

The Structure to save information about a holidays 
.SH "Member Data Documentation"
.PP 
.SS "DateTime WebuntisAPI\&.Types\&.Holiday\&.endTime"
Field containing endtime of holiday 
.SS "int WebuntisAPI\&.Types\&.Holiday\&.id"
Field containing id 
.SS "String WebuntisAPI\&.Types\&.Holiday\&.longname"
Field containing long name of holiday 
.SS "String WebuntisAPI\&.Types\&.Holiday\&.name"
Field containing name of holiday 
.SS "DateTime WebuntisAPI\&.Types\&.Holiday\&.startTime"
Field containing starttime of holiday 

.SH "Author"
.PP 
Generated automatically by Doxygen for WebuntisAPI from the source code\&.
