.TH "WebuntisAPI" 3 "Mit Mai 8 2013" "WU-APP_API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebuntisAPI \- 
.PP
\fBWebuntisAPI\fP Nampespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namensbereiche"

.in +1c
.ti -1c
.RI "package \fBTypes\fP"
.br
.RI "\fI\fBWebuntisAPI::Types\fP Namespase\&. \fP"
.in -1c
.SS "Klassen"

.in +1c
.ti -1c
.RI "class \fBWebUntisConnector\fP"
.br
.ti -1c
.RI "class \fBWebUntisAPI\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
\fBWebuntisAPI\fP Nampespace\&. 

This is the Main Namespace of the WebUntis API\&. It contains the Namespace of the \fBTypes\fP and classes for communication width WebUntis 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für WU-APP_API aus dem Quellcode\&.
